{
 "title": "My π Estimation DevOps Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "timestream_db_name",
    "query": "\"YOUR_TIMESTREAM_DB_NAME_HERE\""
   }
  ]
 },
 "panels": [
  {
   "title": "last average π estimate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT BIN(time, $__interval_ms) AS t_bin, AVG(measure_value::double) AS m_bin\r\nFROM ${timestream_db_name}.sample_app\r\nWHERE time > from_unixtime($__from/1000) and time < LEAST(from_unixtime($__to/1000), now()-1m)\r\nAND measure_name = 'pi'\r\nGROUP BY BIN(time, $__interval_ms)\r\nORDER BY t_bin"
    }
   ]
  },
  {
   "title": "π estimate per host",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "WITH approximate_datapoints AS (\r\n    SELECT BIN(time, $__interval_ms) AS t_bin, host, session_uuid, AVG(measure_value::double) AS m_bin\r\n    FROM ${timestream_db_name}.sample_app\r\n    WHERE $__timeFilter\r\n    AND measure_name = 'pi'\r\n    GROUP BY BIN(time, $__interval_ms), host, session_uuid\r\n)\r\nSELECT host, session_uuid,\r\n  CREATE_TIME_SERIES(t_bin, m_bin) AS \"pi_estimate\"\r\nFROM approximate_datapoints\r\nGROUP BY host, session_uuid\r\nORDER BY host, session_uuid"
    }
   ]
  },
  {
   "title": "π iteration count per host",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawQuery": "WITH approximate_datapoints AS (\r\n    SELECT MAX(time) AS t, host, MAX(measure_value::bigint) AS m\r\n    FROM ${timestream_db_name}.sample_app\r\n    WHERE $__timeFilter\r\n    AND measure_name = 'iteration'\r\n    GROUP BY host\r\n)\r\nSELECT host,\r\n  CREATE_TIME_SERIES(t, m) AS \"iteration\"\r\nFROM approximate_datapoints\r\nGROUP BY host\r\nORDER BY host"
    }
   ]
  },
  {
   "title": "cpu-total: usage_system per host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "WITH approximate_datapoints AS (\r\n    SELECT BIN(time, $__interval_ms) AS t_bin, host, AVG(measure_value::double) AS m_bin\r\n    FROM ${timestream_db_name}.cpu\r\n    WHERE $__timeFilter\r\n    AND cpu = 'cpu-total'\r\n    AND measure_name = 'usage_system'\r\n    GROUP BY BIN(time, $__interval_ms), host\r\n)\r\nSELECT host,\r\n  CREATE_TIME_SERIES(t_bin, m_bin) AS \"usage_system\"\r\nFROM approximate_datapoints\r\nGROUP BY host\r\nORDER BY host"
    }
   ]
  },
  {
   "title": "cpu-total: usage_user per host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "WITH approximate_datapoints AS (\r\n    SELECT BIN(time, $__interval_ms) AS t_bin, host, AVG(measure_value::double) AS m_bin\r\n    FROM ${timestream_db_name}.cpu\r\n    WHERE $__timeFilter\r\n    AND cpu = 'cpu-total'\r\n    AND measure_name = 'usage_user'\r\n    GROUP BY BIN(time, $__interval_ms), host\r\n)\r\nSELECT host,\r\n  CREATE_TIME_SERIES(t_bin, m_bin) AS \"usage_user\"\r\nFROM approximate_datapoints\r\nGROUP BY host\r\nORDER BY host"
    }
   ]
  },
  {
   "title": "memory: available_percent per host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawQuery": "WITH approximate_datapoints AS (\r\n    SELECT BIN(time, $__interval_ms) AS t_bin, host, AVG(measure_value::double) AS m_bin\r\n    FROM ${timestream_db_name}.mem\r\n    WHERE $__timeFilter\r\n    AND measure_name = 'available_percent'\r\n    GROUP BY BIN(time, $__interval_ms), host\r\n)\r\nSELECT host,\r\n  CREATE_TIME_SERIES(t_bin, m_bin) AS \"mem available_percent\"\r\nFROM approximate_datapoints\r\nGROUP BY host\r\nORDER BY host"
    }
   ]
  },
  {
   "title": "memory: free per host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawQuery": "WITH approximate_datapoints AS (\r\n    SELECT BIN(time, $__interval_ms) AS t_bin, host, AVG(measure_value::bigint) AS m_bin\r\n    FROM ${timestream_db_name}.mem\r\n    WHERE $__timeFilter\r\n    AND measure_name = 'free'\r\n    GROUP BY BIN(time, $__interval_ms), host\r\n)\r\nSELECT host,\r\n  CREATE_TIME_SERIES(t_bin, m_bin) AS \"mem free\"\r\nFROM approximate_datapoints\r\nGROUP BY host\r\nORDER BY host"
    }
   ]
  }
 ]
}